version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: healthcare_db
      MYSQL_USER: healthcare_user
      MYSQL_PASSWORD: your_strong_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./backend/database:/var/www/html/database
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  db-init:
    build: 
      context: .
      dockerfile: ./backend/database/init/Dockerfile
    volumes:
      - ./backend/database:/var/www/html/database
      - ./backend/database/init:/docker-entrypoint-init.d
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=healthcare_db
      - DB_USER=healthcare_user
      - DB_PASS=your_strong_password
    depends_on:
      - db
    command: ["/docker-entrypoint-init.d/init-database.sh"]

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      cache_from:
        - healthcare-app-frontend:latest
      args:
        - REACT_APP_API_BASE_URL=http://localhost:8000/api
        - REACT_APP_USER_SERVICE_BASE_URL=http://localhost:8000/api/users
        - REACT_APP_ADMIN_UI_BASE_URL=http://localhost:8000/api
        - REACT_APP_ENV=production
    image: healthcare-app-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://api-gateway:8000/api
      - REACT_APP_USER_SERVICE_BASE_URL=http://user-service:8001/api/users
      - REACT_APP_ADMIN_UI_BASE_URL=http://admin-ui:8007/api
      - REACT_APP_ENV=production
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api-gateway:/var/www/html
      - ./backend/shared:/var/www/shared
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=healthcare_db
      - DB_USER=healthcare_user
      - DB_PASS=your_strong_password
      - JWT_SECRET=healthcare_app_secret_key_2023
    depends_on:
      - user-service
      - appointment-service
      - clinical-service
      - billing-service
      - notification-service
      - storage-service
      - db

  user-service:
    build: ./backend/user-service
    ports:
      - "8001:8001"
    volumes:
      - ./backend/user-service:/var/www/html
      - ./backend/shared:/var/www/shared
      - ./backend/database:/var/www/html/database
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=healthcare_db
      - DB_USER=healthcare_user
      - DB_PASS=your_strong_password
      - JWT_SECRET=healthcare_app_secret_key_2023
    depends_on:
      - db

  appointment-service:
    build: ./backend/appointment-service
    ports:
      - "8002:8002"
    volumes:
      - ./backend/appointment-service:/var/www/html
      - ./backend/shared:/var/www/shared
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=healthcare_db
      - DB_USER=healthcare_user
      - DB_PASS=your_strong_password
      - JWT_SECRET=healthcare_app_secret_key_2023
    depends_on:
      - db

  clinical-service:
    build: ./backend/clinical-service
    ports:
      - "8003:8003"
    volumes:
      - ./backend/clinical-service:/var/www/html
      - ./backend/shared:/var/www/shared
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=healthcare_db
      - DB_USER=healthcare_user
      - DB_PASS=your_strong_password
      - JWT_SECRET=healthcare_app_secret_key_2023
    depends_on:
      - db

  billing-service:
    build: ./backend/billing-service
    ports:
      - "8005:8005"
    volumes:
      - ./backend/billing-service:/var/www/html
      - ./backend/shared:/var/www/shared
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=healthcare_db
      - DB_USER=healthcare_user
      - DB_PASS=your_strong_password
      - JWT_SECRET=healthcare_app_secret_key_2023
    depends_on:
      - db

  notification-service:
    build: ./backend/notification-service
    ports:
      - "8004:8004"
    volumes:
      - ./backend/notification-service:/var/www/html
      - ./backend/shared:/var/www/shared
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=healthcare_db
      - DB_USER=healthcare_user
      - DB_PASS=your_strong_password
      - JWT_SECRET=healthcare_app_secret_key_2023
    depends_on:
      - db

  storage-service:
    build: ./backend/storage
    ports:
      - "8006:8006"
    volumes:
      - ./backend/storage:/var/www/html
      - ./backend/shared:/var/www/shared
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=healthcare_db
      - DB_USER=healthcare_user
      - DB_PASS=your_strong_password
      - JWT_SECRET=healthcare_app_secret_key_2023
    depends_on:
      - db

  admin-ui:
    build: ./backend/admin-ui
    ports:
      - "8007:8007"
    volumes:
      - ./backend/admin-ui:/var/www/html
      - ./backend/shared:/var/www/shared
      - ./backend/user-service:/var/www/user-service
      - ./backend/database:/var/www/database
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=healthcare_db
      - DB_USER=healthcare_user
      - DB_PASS=your_strong_password
      - JWT_SECRET=healthcare_app_secret_key_2023
    depends_on:
      - db

volumes:
  dbdata: